// <auto-generated />
using System;
using MVC.CRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.CRUD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250920155758_userTableWithSeedData")]
    partial class userTableWithSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC.CRUD.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7009656-56b2-4b7a-b423-7a81c2b82f0a"),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            EntryDate = new DateTime(2020, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JoinDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice",
                            Salary = 50000.0
                        },
                        new
                        {
                            Id = new Guid("d7009656-56b2-4b7a-b423-7a81c2b82f0b"),
                            DateOfBirth = new DateTime(1985, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            EntryDate = new DateTime(2018, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JoinDate = new DateTime(2018, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bob",
                            Salary = 60000.0
                        },
                        new
                        {
                            Id = new Guid("d7009656-56b2-4b7a-b423-7a81c2b82f0c"),
                            DateOfBirth = new DateTime(1982, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            EntryDate = new DateTime(2015, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JoinDate = new DateTime(2015, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Charlie",
                            Salary = 75000.0
                        },
                        new
                        {
                            Id = new Guid("d7009656-56b2-4b7a-b423-7a81c2b82f0d"),
                            DateOfBirth = new DateTime(1995, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources",
                            EntryDate = new DateTime(2019, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JoinDate = new DateTime(2019, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "David",
                            Salary = 55000.0
                        },
                        new
                        {
                            Id = new Guid("d7009656-56b2-4b7a-b423-7a81c2b82f0e"),
                            DateOfBirth = new DateTime(1988, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            EntryDate = new DateTime(2017, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JoinDate = new DateTime(2017, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eve",
                            Salary = 70000.0
                        });
                });

            modelBuilder.Entity("MVC.CRUD.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "10 Main St",
                            City = "City1",
                            DateOfBirth = new DateTime(1989, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user1@example.com",
                            FirstName = "First1",
                            Gender = "Female",
                            LastName = "Last1",
                            Password = "P@ssword1",
                            PhoneNumber = "555-00001",
                            ProfilePicture = "profile1.jpg",
                            Role = "User",
                            Salary = 31000.0,
                            State = "State1",
                            Username = "user1",
                            ZipCode = "10001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "20 Main St",
                            City = "City2",
                            DateOfBirth = new DateTime(1988, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user2@example.com",
                            FirstName = "First2",
                            Gender = "Male",
                            LastName = "Last2",
                            Password = "P@ssword2",
                            PhoneNumber = "555-00002",
                            ProfilePicture = "profile2.jpg",
                            Role = "User",
                            Salary = 32000.0,
                            State = "State2",
                            Username = "user2",
                            ZipCode = "10002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "30 Main St",
                            City = "City3",
                            DateOfBirth = new DateTime(1987, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user3@example.com",
                            FirstName = "First3",
                            Gender = "Female",
                            LastName = "Last3",
                            Password = "P@ssword3",
                            PhoneNumber = "555-00003",
                            ProfilePicture = "profile3.jpg",
                            Role = "Admin",
                            Salary = 33000.0,
                            State = "State3",
                            Username = "user3",
                            ZipCode = "10003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "40 Main St",
                            City = "City4",
                            DateOfBirth = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user4@example.com",
                            FirstName = "First4",
                            Gender = "Male",
                            LastName = "Last4",
                            Password = "P@ssword4",
                            PhoneNumber = "555-00004",
                            ProfilePicture = "profile4.jpg",
                            Role = "User",
                            Salary = 34000.0,
                            State = "State4",
                            Username = "user4",
                            ZipCode = "10004"
                        },
                        new
                        {
                            Id = 5,
                            Address = "50 Main St",
                            City = "City5",
                            DateOfBirth = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user5@example.com",
                            FirstName = "First5",
                            Gender = "Female",
                            LastName = "Last5",
                            Password = "P@ssword5",
                            PhoneNumber = "555-00005",
                            ProfilePicture = "profile5.jpg",
                            Role = "User",
                            Salary = 35000.0,
                            State = "State5",
                            Username = "user5",
                            ZipCode = "10005"
                        },
                        new
                        {
                            Id = 6,
                            Address = "60 Main St",
                            City = "City6",
                            DateOfBirth = new DateTime(1984, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user6@example.com",
                            FirstName = "First6",
                            Gender = "Male",
                            LastName = "Last6",
                            Password = "P@ssword6",
                            PhoneNumber = "555-00006",
                            ProfilePicture = "profile6.jpg",
                            Role = "Admin",
                            Salary = 36000.0,
                            State = "State6",
                            Username = "user6",
                            ZipCode = "10006"
                        },
                        new
                        {
                            Id = 7,
                            Address = "70 Main St",
                            City = "City7",
                            DateOfBirth = new DateTime(1983, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user7@example.com",
                            FirstName = "First7",
                            Gender = "Female",
                            LastName = "Last7",
                            Password = "P@ssword7",
                            PhoneNumber = "555-00007",
                            ProfilePicture = "profile7.jpg",
                            Role = "User",
                            Salary = 37000.0,
                            State = "State7",
                            Username = "user7",
                            ZipCode = "10007"
                        },
                        new
                        {
                            Id = 8,
                            Address = "80 Main St",
                            City = "City8",
                            DateOfBirth = new DateTime(1982, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user8@example.com",
                            FirstName = "First8",
                            Gender = "Male",
                            LastName = "Last8",
                            Password = "P@ssword8",
                            PhoneNumber = "555-00008",
                            ProfilePicture = "profile8.jpg",
                            Role = "User",
                            Salary = 38000.0,
                            State = "State8",
                            Username = "user8",
                            ZipCode = "10008"
                        },
                        new
                        {
                            Id = 9,
                            Address = "90 Main St",
                            City = "City9",
                            DateOfBirth = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user9@example.com",
                            FirstName = "First9",
                            Gender = "Female",
                            LastName = "Last9",
                            Password = "P@ssword9",
                            PhoneNumber = "555-00009",
                            ProfilePicture = "profile9.jpg",
                            Role = "Admin",
                            Salary = 39000.0,
                            State = "State9",
                            Username = "user9",
                            ZipCode = "10009"
                        },
                        new
                        {
                            Id = 10,
                            Address = "100 Main St",
                            City = "City10",
                            DateOfBirth = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user10@example.com",
                            FirstName = "First10",
                            Gender = "Male",
                            LastName = "Last10",
                            Password = "P@ssword10",
                            PhoneNumber = "555-00010",
                            ProfilePicture = "profile10.jpg",
                            Role = "User",
                            Salary = 40000.0,
                            State = "State10",
                            Username = "user10",
                            ZipCode = "10010"
                        },
                        new
                        {
                            Id = 11,
                            Address = "110 Main St",
                            City = "City11",
                            DateOfBirth = new DateTime(1979, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user11@example.com",
                            FirstName = "First11",
                            Gender = "Female",
                            LastName = "Last11",
                            Password = "P@ssword11",
                            PhoneNumber = "555-00011",
                            ProfilePicture = "profile11.jpg",
                            Role = "User",
                            Salary = 41000.0,
                            State = "State11",
                            Username = "user11",
                            ZipCode = "10011"
                        },
                        new
                        {
                            Id = 12,
                            Address = "120 Main St",
                            City = "City12",
                            DateOfBirth = new DateTime(1978, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user12@example.com",
                            FirstName = "First12",
                            Gender = "Male",
                            LastName = "Last12",
                            Password = "P@ssword12",
                            PhoneNumber = "555-00012",
                            ProfilePicture = "profile12.jpg",
                            Role = "Admin",
                            Salary = 42000.0,
                            State = "State12",
                            Username = "user12",
                            ZipCode = "10012"
                        },
                        new
                        {
                            Id = 13,
                            Address = "130 Main St",
                            City = "City13",
                            DateOfBirth = new DateTime(1977, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user13@example.com",
                            FirstName = "First13",
                            Gender = "Female",
                            LastName = "Last13",
                            Password = "P@ssword13",
                            PhoneNumber = "555-00013",
                            ProfilePicture = "profile13.jpg",
                            Role = "User",
                            Salary = 43000.0,
                            State = "State13",
                            Username = "user13",
                            ZipCode = "10013"
                        },
                        new
                        {
                            Id = 14,
                            Address = "140 Main St",
                            City = "City14",
                            DateOfBirth = new DateTime(1976, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user14@example.com",
                            FirstName = "First14",
                            Gender = "Male",
                            LastName = "Last14",
                            Password = "P@ssword14",
                            PhoneNumber = "555-00014",
                            ProfilePicture = "profile14.jpg",
                            Role = "User",
                            Salary = 44000.0,
                            State = "State14",
                            Username = "user14",
                            ZipCode = "10014"
                        },
                        new
                        {
                            Id = 15,
                            Address = "150 Main St",
                            City = "City15",
                            DateOfBirth = new DateTime(1975, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user15@example.com",
                            FirstName = "First15",
                            Gender = "Female",
                            LastName = "Last15",
                            Password = "P@ssword15",
                            PhoneNumber = "555-00015",
                            ProfilePicture = "profile15.jpg",
                            Role = "Admin",
                            Salary = 45000.0,
                            State = "State15",
                            Username = "user15",
                            ZipCode = "10015"
                        },
                        new
                        {
                            Id = 16,
                            Address = "160 Main St",
                            City = "City16",
                            DateOfBirth = new DateTime(1974, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user16@example.com",
                            FirstName = "First16",
                            Gender = "Male",
                            LastName = "Last16",
                            Password = "P@ssword16",
                            PhoneNumber = "555-00016",
                            ProfilePicture = "profile16.jpg",
                            Role = "User",
                            Salary = 46000.0,
                            State = "State16",
                            Username = "user16",
                            ZipCode = "10016"
                        },
                        new
                        {
                            Id = 17,
                            Address = "170 Main St",
                            City = "City17",
                            DateOfBirth = new DateTime(1973, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user17@example.com",
                            FirstName = "First17",
                            Gender = "Female",
                            LastName = "Last17",
                            Password = "P@ssword17",
                            PhoneNumber = "555-00017",
                            ProfilePicture = "profile17.jpg",
                            Role = "User",
                            Salary = 47000.0,
                            State = "State17",
                            Username = "user17",
                            ZipCode = "10017"
                        },
                        new
                        {
                            Id = 18,
                            Address = "180 Main St",
                            City = "City18",
                            DateOfBirth = new DateTime(1972, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user18@example.com",
                            FirstName = "First18",
                            Gender = "Male",
                            LastName = "Last18",
                            Password = "P@ssword18",
                            PhoneNumber = "555-00018",
                            ProfilePicture = "profile18.jpg",
                            Role = "Admin",
                            Salary = 48000.0,
                            State = "State18",
                            Username = "user18",
                            ZipCode = "10018"
                        },
                        new
                        {
                            Id = 19,
                            Address = "190 Main St",
                            City = "City19",
                            DateOfBirth = new DateTime(1971, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user19@example.com",
                            FirstName = "First19",
                            Gender = "Female",
                            LastName = "Last19",
                            Password = "P@ssword19",
                            PhoneNumber = "555-00019",
                            ProfilePicture = "profile19.jpg",
                            Role = "User",
                            Salary = 49000.0,
                            State = "State19",
                            Username = "user19",
                            ZipCode = "10019"
                        },
                        new
                        {
                            Id = 20,
                            Address = "200 Main St",
                            City = "City20",
                            DateOfBirth = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user20@example.com",
                            FirstName = "First20",
                            Gender = "Male",
                            LastName = "Last20",
                            Password = "P@ssword20",
                            PhoneNumber = "555-00020",
                            ProfilePicture = "profile20.jpg",
                            Role = "User",
                            Salary = 50000.0,
                            State = "State20",
                            Username = "user20",
                            ZipCode = "10020"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
